> Copyright 2025 Giovanni Squillero <<giovanni.squillero@polito.it>>  
> SPDX-License-Identifier: `0BSD`

In [2]:
from itertools import accumulate
from icecream import ic
import numpy as np
from tqdm.auto import tqdm
from matplotlib import pyplot as plt

# 0-1 Multiple Knapsack Problem

see: [https://en.wikipedia.org/wiki/Knapsack_problem](https://en.wikipedia.org/wiki/Knapsack_problem)

In [3]:
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

In [26]:
NUM_ITEMS = 10
DIMENSIONS = 5
MAX_STEPS = 20_000

WEIGHTS = np.random.randint(1, 50 + 1, size=(NUM_ITEMS, DIMENSIONS))
MAX_WEIGHTS = np.full(DIMENSIONS, NUM_ITEMS * 20)
VALUES = np.random.randint(1, 100 + 1, size=NUM_ITEMS)

In [27]:
def evaluate(knapsack):
    if all(np.sum(WEIGHTS[knapsack], axis=0) < MAX_WEIGHTS):
        return np.sum(VALUES[knapsack])
    else:
        return -1

In [28]:
WEIGHTS

array([[38, 45, 41, 47, 14],
       [39, 25, 20,  2, 39],
       [ 6, 17, 25, 28,  2],
       [35, 37,  5,  1, 40],
       [12, 36, 45, 23, 47],
       [31, 11, 10,  3, 14],
       [16, 10, 29, 10, 12],
       [30, 41,  1,  5, 20],
       [ 8, 43, 12,  1, 20],
       [28, 43, 37, 47, 37]])

In [29]:
MAX_WEIGHTS

array([200, 200, 200, 200, 200])

In [30]:
VALUES

array([76, 37, 49, 44, 56, 28, 79,  6, 61, 20])

In [24]:
solution = np.array([True, True, True, False, False])
evaluate(solution)

-1

In [20]:
solution

array([False, False, False, False, False])